// Simulation de session console pour chaque projet.
// Chaque entrée est soit une ligne de "sortie" du programme,
// soit une interaction utilisateur marquée { input: true }.

export interface TerminalLine {
  text: string;
  input?: boolean;   // ligne saisie par l'utilisateur
  delay?: number;    // délai avant affichage (ms), défaut 80
  color?: string;
}

export type TerminalScript = TerminalLine[];

export const terminalScripts: Record<string, TerminalScript> = {

  "calcul-romain": [
    { text: "=== CALCUL ROMAIN ===" },
    { text: "" },
    { text: "1) Arabe → Romain" },
    { text: "2) Romain → Arabe" },
    { text: "Votre choix : ", delay: 400 },
    { text: "1", input: true, delay: 600 },
    { text: "Entrez un nombre (1-3999) : ", delay: 300 },
    { text: "2024", input: true, delay: 700 },
    { text: "" },
    { text: "2024  →  MMXXIV", color: "#00ff41", delay: 200 },
    { text: "" },
    { text: "Autre conversion ? (o/n) : ", delay: 500 },
    { text: "o", input: true, delay: 600 },
    { text: "Votre choix : ", delay: 200 },
    { text: "2", input: true, delay: 500 },
    { text: "Entrez un nombre romain : ", delay: 300 },
    { text: "XIV", input: true, delay: 700 },
    { text: "" },
    { text: "XIV  →  14", color: "#00ff41", delay: 200 },
    { text: "" },
    { text: "Autre conversion ? (o/n) : ", delay: 500 },
    { text: "n", input: true, delay: 500 },
    { text: "Au revoir !", color: "#00ff4166", delay: 200 },
  ],

  "traduction-morse": [
    { text: "=== TRADUCTION MORSE ===" },
    { text: "" },
    { text: "1) Texte → Morse" },
    { text: "2) Morse → Texte" },
    { text: "Choix : ", delay: 400 },
    { text: "1", input: true, delay: 600 },
    { text: "Texte : ", delay: 300 },
    { text: "HELLO WORLD", input: true, delay: 800 },
    { text: "" },
    { text: ".... . .-.. .-.. ---  .-- --- .-. .-.. -..", color: "#00ffff", delay: 300 },
    { text: "" },
    { text: "Choix : ", delay: 500 },
    { text: "2", input: true, delay: 600 },
    { text: "Morse : ", delay: 300 },
    { text: "... --- ...", input: true, delay: 800 },
    { text: "" },
    { text: "SOS", color: "#00ffff", delay: 300 },
  ],

  "forme-geometriques": [
    { text: "=== FORMES GÉOMÉTRIQUES ===" },
    { text: "" },
    { text: "1) Cercle   2) Rectangle   3) Triangle" },
    { text: "Choix : ", delay: 400 },
    { text: "1", input: true, delay: 600 },
    { text: "Rayon : ", delay: 300 },
    { text: "5", input: true, delay: 500 },
    { text: "" },
    { text: "── Cercle ──────────────────", color: "#00ff4166" },
    { text: "Rayon      :  5.00", color: "#00ff41" },
    { text: "Diamètre   :  10.00", color: "#00ff41" },
    { text: "Périmètre  :  31.42", color: "#00ff41" },
    { text: "Aire       :  78.54", color: "#00ff41" },
    { text: "────────────────────────────", color: "#00ff4166" },
    { text: "" },
    { text: "Choix : ", delay: 500 },
    { text: "2", input: true, delay: 600 },
    { text: "Longueur : ", delay: 300 },
    { text: "6", input: true, delay: 400 },
    { text: "Largeur : ", delay: 200 },
    { text: "4", input: true, delay: 400 },
    { text: "" },
    { text: "── Rectangle ───────────────", color: "#00ff4166" },
    { text: "Longueur   :  6.00", color: "#00ff41" },
    { text: "Largeur    :  4.00", color: "#00ff41" },
    { text: "Périmètre  :  20.00", color: "#00ff41" },
    { text: "Aire       :  24.00", color: "#00ff41" },
    { text: "────────────────────────────", color: "#00ff4166" },
  ],

  "etude-parabole": [
    { text: "=== ÉTUDE DE PARABOLE ===" },
    { text: "f(x) = ax² + bx + c" },
    { text: "" },
    { text: "a = ", delay: 400 },
    { text: "1", input: true, delay: 500 },
    { text: "b = ", delay: 200 },
    { text: "-3", input: true, delay: 500 },
    { text: "c = ", delay: 200 },
    { text: "2", input: true, delay: 500 },
    { text: "" },
    { text: "── Analyse ─────────────────", color: "#00ff4166" },
    { text: "Discriminant  Δ = 1", color: "#00ff41" },
    { text: "Racines    x1 = 1.00   x2 = 2.00", color: "#00ff41" },
    { text: "Sommet     S  = (1.50 ; -0.25)", color: "#00ffff" },
    { text: "Axe sym.   x  = 1.50", color: "#00ff41" },
    { text: "Concavité       vers le haut (a > 0)", color: "#00ff41" },
    { text: "────────────────────────────", color: "#00ff4166" },
    { text: "" },
    { text: "  x |  -1  |  0  |  1  |  2  |  3 ", color: "#00ff4166" },
    { text: "f(x)|   6  |  2  |  0  | -1  |  0  |  2", color: "#00ff4166" },
  ],

  "star-wars": [
    { text: "=== STAR WARS — GESTION DE FLOTTE ===" },
    { text: "Chargement des données...", color: "#00ff4166", delay: 600 },
    { text: "✓ carte_vaisseau.txt    [12 vaisseaux]", color: "#00ff41" },
    { text: "✓ carte_amelioration.txt [8 améliorations]", color: "#00ff41" },
    { text: "" },
    { text: "1) Afficher flotte    2) Améliorer vaisseau" },
    { text: "3) Statistiques       4) Quitter" },
    { text: "Choix : ", delay: 400 },
    { text: "1", input: true, delay: 600 },
    { text: "" },
    { text: "NOM              CLASSE        PV   ATK  DEF", color: "#00ffff" },
    { text: "─────────────────────────────────────────────", color: "#1a2332" },
    { text: "Millennium Falcon  Fregate     150   85   60", color: "#00ff41" },
    { text: "X-Wing             Chasseur     80   95   40", color: "#00ff41" },
    { text: "Star Destroyer     Cuirasse    400   70   90", color: "#ff0040" },
    { text: "Y-Wing             Bombardier  100   80   50", color: "#00ff41" },
    { text: "TIE Fighter        Chasseur     60  100   25", color: "#ffb300" },
    { text: "─────────────────────────────────────────────", color: "#1a2332" },
    { text: "" },
    { text: "Choix : ", delay: 400 },
    { text: "3", input: true, delay: 600 },
    { text: "" },
    { text: "Total vaisseaux  : 12", color: "#00ff41" },
    { text: "PV moyen         : 148", color: "#00ff41" },
    { text: "ATK max          : 100  (TIE Fighter)", color: "#00ffff" },
    { text: "DEF max          :  90  (Star Destroyer)", color: "#00ffff" },
  ],

  "javanais": [
    { text: "=== PARLONS JAVANAIS ===" },
    { text: "" },
    { text: "Entrez une phrase : ", delay: 400 },
    { text: "Bonjour tout le monde", input: true, delay: 800 },
    { text: "" },
    { text: "Traduction :", color: "#00ff4166" },
    { text: "Bavonjavoir tavoutlave mavonde", color: "#00ffff", delay: 300 },
    { text: "" },
    { text: "Entrez une phrase : ", delay: 400 },
    { text: "Informatique", input: true, delay: 700 },
    { text: "" },
    { text: "Traduction :", color: "#00ff4166" },
    { text: "Inavformavatiquave", color: "#00ffff", delay: 300 },
  ],

  "algorithme-tableau": [
    { text: "=== ALGORITHMIQUE SUR TABLEAU ===" },
    { text: "" },
    { text: "1) Tri à bulles     2) Recherche binaire" },
    { text: "3) Min/Max/Moyenne  4) Quitter" },
    { text: "Choix : ", delay: 400 },
    { text: "1", input: true, delay: 600 },
    { text: "Taille du tableau : ", delay: 300 },
    { text: "8", input: true, delay: 500 },
    { text: "" },
    { text: "Tableau initial  : [42, 7, 19, 3, 88, 15, 64, 31]", color: "#00ff4166" },
    { text: "Étape 1  : [7, 19, 3, 42, 15, 64, 31, 88]", color: "#ffb300" },
    { text: "Étape 2  : [7, 3, 19, 15, 42, 31, 64, 88]", color: "#ffb300" },
    { text: "Étape 3  : [3, 7, 15, 19, 31, 42, 64, 88]", color: "#ffb300" },
    { text: "" },
    { text: "Tableau trié     : [3, 7, 15, 19, 31, 42, 64, 88]", color: "#00ff41" },
    { text: "Comparaisons     : 28", color: "#00ff41" },
    { text: "Échanges         : 12", color: "#00ff41" },
  ],

  "escadrille-raf": [
    { text: "=== ESCADRILLE RAF ===" },
    { text: "Chargement...", color: "#00ff4166", delay: 500 },
    { text: "✓ aircraft.txt  [24 appareils]", color: "#00ff41" },
    { text: "✓ staff.txt     [18 pilotes]", color: "#00ff41" },
    { text: "" },
    { text: "1) Liste appareils  2) Liste pilotes" },
    { text: "3) Statistiques     4) Résultats", delay: 300 },
    { text: "Choix : ", delay: 400 },
    { text: "3", input: true, delay: 600 },
    { text: "" },
    { text: "── Statistiques ─────────────────", color: "#00ff4166" },
    { text: "Appareils          :  24", color: "#00ff41" },
    { text: "  - Chasseurs      :  10", color: "#00ff41" },
    { text: "  - Bombardiers    :   8", color: "#00ff41" },
    { text: "  - Reconnaissance :   6", color: "#00ff41" },
    { text: "Pilotes actifs     :  18", color: "#00ff41" },
    { text: "Heures vol moy.    :  847 h", color: "#00ffff" },
    { text: "Top pilote         :  Cdt. Harrison (1240 h)", color: "#ffb300" },
    { text: "─────────────────────────────────", color: "#00ff4166" },
  ],

  "traitements-matrice": [
    { text: "=== TRAITEMENTS MATRICE ===" },
    { text: "" },
    { text: "1) Charger matrice   2) Addition" },
    { text: "3) Multiplication    4) Transposée" },
    { text: "Choix : ", delay: 400 },
    { text: "1", input: true, delay: 600 },
    { text: "Lignes : ", delay: 300 },
    { text: "3", input: true, delay: 400 },
    { text: "Colonnes : ", delay: 200 },
    { text: "3", input: true, delay: 400 },
    { text: "" },
    { text: "Matrice A :", color: "#00ff4166" },
    { text: " [ 1  2  3 ]", color: "#00ff41" },
    { text: " [ 4  5  6 ]", color: "#00ff41" },
    { text: " [ 7  8  9 ]", color: "#00ff41" },
    { text: "" },
    { text: "Choix : ", delay: 400 },
    { text: "4", input: true, delay: 500 },
    { text: "" },
    { text: "Transposée A^T :", color: "#00ff4166" },
    { text: " [ 1  4  7 ]", color: "#00ffff" },
    { text: " [ 2  5  8 ]", color: "#00ffff" },
    { text: " [ 3  6  9 ]", color: "#00ffff" },
  ],

  "canne-a-sucre": [
    { text: "=== CANNE À SUCRE — OPTIMISATION ===" },
    { text: "Chargement du problème...", color: "#00ff4166", delay: 500 },
    { text: "" },
    { text: "Système : A·X = B", color: "#00ff4166" },
    { text: "" },
    { text: " [ 2   1  -1 ] [ x1 ]   [  8 ]", color: "#00ff41" },
    { text: " [-3  -1   2 ] [ x2 ] = [ -11]", color: "#00ff41" },
    { text: " [-2   1   2 ] [ x3 ]   [ -3 ]", color: "#00ff41" },
    { text: "" },
    { text: "Décomposition LUP...", color: "#00ff4166", delay: 600 },
    { text: "✓ Pivot trouvé", color: "#00ff41", delay: 300 },
    { text: "" },
    { text: "Solution :", color: "#00ffff" },
    { text: "  x1 =  2.00", color: "#00ff41" },
    { text: "  x2 =  3.00", color: "#00ff41" },
    { text: "  x3 = -1.00", color: "#00ff41" },
    { text: "" },
    { text: "Vérification A·X = B : ✓ OK", color: "#00ff41" },
  ],

  "calculatrice-multi": [
    { text: "=== CALCULATRICE MULTI-OPÉRANTE ===" },
    { text: "(C++) Entrez une expression :" },
    { text: "" },
    { text: "> ", delay: 400 },
    { text: "12.5 + 7.3", input: true, delay: 700 },
    { text: "= 19.80", color: "#00ff41", delay: 200 },
    { text: "> ", delay: 300 },
    { text: "100 / 4", input: true, delay: 600 },
    { text: "= 25.00", color: "#00ff41", delay: 200 },
    { text: "> ", delay: 300 },
    { text: "3.14 * 5 * 5", input: true, delay: 700 },
    { text: "= 78.50", color: "#00ff41", delay: 200 },
    { text: "> ", delay: 300 },
    { text: "2 ^ 10", input: true, delay: 600 },
    { text: "= 1024.00", color: "#00ff41", delay: 200 },
  ],

  "systeme-solaire": [
    { text: "=== SYSTÈME SOLAIRE ===" },
    { text: "(C++) Modélisation orientée objet" },
    { text: "" },
    { text: "Objets créés :", color: "#00ff4166", delay: 400 },
    { text: "  Etoile     : Soleil   (masse: 1.989e30 kg)", color: "#ffb300" },
    { text: "  Planete    : Mercure  (d: 57.9M km)", color: "#00ff41" },
    { text: "  Planete    : Venus    (d: 108.2M km)", color: "#00ff41" },
    { text: "  Planete    : Terre    (d: 149.6M km)", color: "#0080ff" },
    { text: "  Planete    : Mars     (d: 227.9M km)", color: "#ff0040" },
    { text: "  Planete    : Jupiter  (d: 778.5M km)", color: "#ffb300" },
    { text: "  Satellite  : Lune     (planete: Terre)", color: "#00ff4166" },
    { text: "" },
    { text: "Distance Terre-Soleil : 149.6 millions km", color: "#00ffff" },
    { text: "Période Terre         : 365.25 jours", color: "#00ffff" },
    { text: "Vitesse orbitale      : 29.78 km/s", color: "#00ffff" },
  ],

  "dongeon-dragon": [
    { text: "=== DONGEON & DRAGON ===" },
    { text: "(C++) Simulation de combat RPG" },
    { text: "" },
    { text: "Héros créé : Aragorn [Guerrier] PV:100 ATK:45 DEF:30", color: "#00ff41" },
    { text: "" },
    { text: "Un Gobelin (PV:30 ATK:12) apparaît !", color: "#ff0040", delay: 600 },
    { text: "" },
    { text: "Tour 1 —", color: "#00ff4166" },
    { text: "  Aragorn attaque : 45 - 5 (DEF) = 40 dégâts", color: "#00ff41" },
    { text: "  Gobelin : PV 30 → 0  ☠", color: "#ff0040", delay: 400 },
    { text: "" },
    { text: "✓ Victoire ! +15 XP  +3 pièces d'or", color: "#ffb300", delay: 300 },
    { text: "" },
    { text: "Un Troll (PV:80 ATK:25) apparaît !", color: "#ff0040", delay: 800 },
    { text: "" },
    { text: "Tour 1 —", color: "#00ff4166" },
    { text: "  Aragorn attaque : 40 dégâts → Troll PV 80→40", color: "#00ff41" },
    { text: "  Troll attaque   : 25 - 10 (DEF) = 15 → Aragorn PV 100→85", color: "#ff0040" },
    { text: "Tour 2 —", color: "#00ff4166" },
    { text: "  Aragorn attaque : 40 dégâts → Troll PV 40→0  ☠", color: "#00ff41" },
    { text: "" },
    { text: "✓ Victoire ! +30 XP  +8 pièces d'or", color: "#ffb300", delay: 300 },
  ],
};
